name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. GitHub 저장소의 코드를 체크아웃
    - name: Check out the repository
      uses: actions/checkout@v4

    # 2. JDK 17 설치
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    # 3. Gradle로 빌드
    - name: Build with Gradle
      run: ./gradlew clean bootJar

    # 4. Docker Hub에 로그인 (공식 로그인 액션 사용)
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 5. Docker 이미지를 빌드
    - name: Build the Docker image
      run: docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/aiwa_spring:v1" .

    # 6. Docker Hub에 푸시
    - name: Push Docker image to Docker Hub
      run: docker push "${{ secrets.DOCKERHUB_USERNAME }}/aiwa_spring:v1"
